# preload = ~/Documents/Wallpapers/dark_souls_dark.jpg
# preload = ~/Documents/Wallpapers/desk-gruvbox-material.jpg
# preload = ~/Documents/Wallpapers/surreal_girl_existential.png
# preload = ~/Documents/Wallpapers/sushi.jpg
# preload = ~/Documents/Wallpapers/starry-sky.png

# wallpaper = DP-1,~/Documents/Wallpapers/dark_souls_dark.jpg

wallpaper {
    monitor = DP-1
    path = ~/Documents/Wallpapers/dark_souls_dark.jpg
    fit_mode = cover
}

splash = false
