## Programs and app-specific configs ##

$terminal = ghostty
$fileManager = nautilus
$menu = rofi
$lockscreen = hyprlock
$colorpicker = hyprpicker
$screenshot = hyprshot

# For Nautilus, NautilusPreviewer, ... open floating
# For 
