## Startup ##
source = ./theme.conf

# exec-once = kdeconnect-indicator
exec-once = xrandr --output DP-1 --primary
exec-once = eval $(ssh-agent -s);
exec-once = ssh-add ~/.ssh/id_rsa
exec-once = ssh-add ~/.ssh/id_ed25519
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprctl setcursor $cursor
exec-once = waybar
exec-once = pianoterm -n Roland -c $HOME/.config/pianoterm/config_tabs
exec-once = kiwix-serve -d -p 1024 $MEDIA/Kiwix/wikipedia_en_all_maxi_2026-02.zim $MEDIA/Kiwix/archlinux_en_all_maxi_2025-09.zim

# exec-once = hyprpm reload -n
