## Look and Feel ##
source = ./colors.conf

$cursor = Bibata-Original-Classic 24

general {
    layout = dwindle
    gaps_in = 2
    gaps_out = 2
    border_size = 0
}

dwindle {
    force_split = 2 # split to the right
}

group {
    groupbar {
        blur = true
        height = 24
        font_size = 8
        indicator_height = 1
        keep_upper_gap = false
        col.active = $lightGrayGradient
        col.inactive = $grayGradient
        col.locked_active = $lightGrayGradient
        col.locked_inactive = $grayGradient
    }
}

decoration {
    rounding = 1
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
    }
}

cursor {
    inactive_timeout = 30
    no_hardware_cursors = 1
}

misc {
    font_family = Ioskeley Mono
    disable_hyprland_logo = true
}

binds {
    workspace_center_on = 1
}

# Windows

# tabs
windowrule {
  name = windowrule-1
  group = set always
  match:class = ^(FreeTube|org.gnome.Nautilus)$
}

# float
windowrule {
  name = windowrule-2
  float = on
  match:class = ^(org.gnome.NautilusPreviewer|Eog|Gedit|Evince|Pavucontrol)$
}

windowrule {
  name = windowrule-4
  size = 600 800
  float = on
  match:title = ^(scratchpad)$
}

# Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
