[ids]
*

[main]
capslock = overload(control, esc) 
esc = capslock
leftalt = leftmeta
leftmeta = leftalt
rightalt = oneshot(altgr)
\ = =
' = \
= = 102nd

f7 = previoussong
f8 = playpause
f9 = nextsong
f10 = mute
f11 = volumedown
f12 = volumeup

previoussong = f7
playpause = f8
nextsong = f9
mute = f10
volumedown = f11
volumeup = f12
