
# -*- conf -*-
[main]
#include=/usr/share/foot/themes/deus
include=/usr/share/foot/themes/aeroroot

term=xterm-256color
font=IoskeleyMono:size=12
initial-color-theme=dark

[cursor]
style=beam

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.99
