# -*- conf -*-
[main]
include=/usr/share/foot/themes/aeroroot

term=xterm-256color
font=IoskeleyMono:size=11
initial-color-theme=light

[cursor]
style=beam

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.99
